[tool.poetry]
name = "stegano"
version = "0.9.7"
description = "A pure Python Steganography module."
authors = ["Cédric Bonhomme <cedric@cedricbonhomme.org>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
pillow = "^6.2.1"
piexif = "^1.1.3"
crayons = "^0.3.0"

[tool.poetry.dev-dependencies]
mypy = "^0.750"
nose = "^1.3.7"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
